### ISSUE TITLE
最近在学习SSL/TSL的内容 想提一种攻击是否可能 或者是否存在

### ISSUE THREAD

**Issue by BlackC0** [zq99299/note-book2#2]
看到笔记里面TLS1.3由于要兼容TLS1.2本质上是伪装成TLS1.2 进行扩展
如果服务器支持TLS1.3再在后续连接中升级成TLS1.3进行连接
那么如果中间人截取了TLS握手的内容 把客户端提供的额外内容删掉 降级为TLS1.2 
服务器识别到是 TLS1.2 也只会以TLS1.2进行握手
那么是否可能通过之前TLS1.2存在的漏洞进行攻击呢？（我不太清楚TLS1.2存在哪些漏洞）

**Comment by BlackC0** [comment]
抱歉 阅读不仔细 文章中已经提及TLS1.3有降级保护机制 此issue将关闭

**Comment by zq99299** [comment]
> 

我也记不太清了，但是感觉这个  截取   是前面讲到过的  安全 部分，机密性、完整性之类的范畴来保障。
